### ISSUE TITLE
Getting loading not defined error

### ISSUE THREAD

**Issue by khat33b** [yoobi55/Hulu-UI-with-React#1]
When I run the program for the first time, I get the following error:

```
./src/components/Screen.js
  Line 134:  'loading' is not defined  no-undef
```

How to solve this?

**Comment by yoobi55** [comment]
Oops, my oversight. That class needs initial state of `loading`

This should fix the issue
```
state = {
    catWidth: [],
    toLeft: 40,
    currentSlideIndex: 0,
    currentItem: 0,
    loading: false //<---Add this
  }; 
```

Hope this helps, thanks!  Let me know if this doesn't fix the issue!

_Just a note, I wrote this just to prove the concept for my blog, therefore, it is not production-ready. If you are planning on using this for production, I strongly recommend implementing at least type-checking (flow, `PropTypes`, whatever you like to use), data management(redux or mobx or whatever) and testing. How I wrote there does not follow a good MVC pattern._

**Comment by khat33b** [comment]
It didn't solve the problem. I just wanted to see how this UI looks on my screen. I thought that it would at least run.

**Comment by yoobi55** [comment]
Odd.. what does it say when you run it? I'll clone it and try reproducing the error.

**Comment by khat33b** [comment]
I am getting the same error as before. Just clone the project and try running it. You'll get it too.

**Comment by yoobi55** [comment]
So the solution I suggest works. But you still need to add that `loading` state in the render method.
```
render() {
    const { toLeft, currentSlideIndex, currentItem, loading //<-this } = this.state;
....
```
It runs fine on my machine, so I'm closing the issue. The repo is updated, and if you keep running into the same issue, please let me know. Thanks!
